CREATE TABLE pricing_sheet_line_item(
    id INT NOT NULL IDENTITY PRIMARY KEY,
    name VARCHAR(MAX) NOT NULL,
    pricing_sheet_id INT NOT NULL,
    price FLOAT NOT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE pricing_sheet(
    id INT NOT NULL IDENTITY PRIMARY KEY,
    name VARCHAR(MAX) NOT NULL,
    user_id INT NULL,
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE TABLE users(
    id INT NOT NULL IDENTITY PRIMARY KEY,
    name VARCHAR(MAX) NOT NULL,
    pass VARCHAR(MAX) NOT NULL, -- THIS SHOULD BE CHANGED TO HANDLE PROPER PASSWORD STORAGE AT A LATER TIME
    created_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_on DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)